name: Update Projects JSON

on:
  push:
    paths:
      - 'projects/**'         # Watch the projects folder for any changes
      - 'descriptions.txt'   # Watch the descriptions file for changes

permissions:
  contents: write  # Grant write permissions for repository contents

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'  # Specify Node.js version

      # 3. Run updateProjects.js
      - name: Run updateProjects.js
        run: node scripts/updateProjects.js

      # 4. Configure Git
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # 5. Commit and Push Changes
      - name: Commit and Push changes
        run: |
          git add projects.json
          git commit -m "Automated update of projects.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
